import type { Metadata } from 'next';
import './globals.css';
import './video-react.css';
import Footer from '@/components/home/Footer';
import '@fortawesome/fontawesome-free/css/all.min.css'
import '../style/main.css';
import { GoogleTagManager } from '@next/third-parties/google'

export const metadata: Metadata = {
  title: 'Mzar',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" id='root'>
      <GoogleTagManager gtmId='GTM-WS294KJ' />
      <body className="w-full" suppressHydrationWarning={true}>
        <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WS294KJ" height="0" width="0" style={{ display: 'none', visibility: 'hidden' }}></iframe></noscript>
        <>{children}</>
        <Footer />
      </body>
    </html>
  );
}
